id: Triplet
pretrained: null
model:
    name: TripletNet
    args:
        extractor:
            name: EfficientNetExtractor
            args:
                version: 0
optimizer:
    name: Adam
    args:
        lr: 0.001
loss:
    name: TripletLoss
    args:
        margin: 1.0
metric:
    name: MeanAP
    args:
        query:
            name: AIC2020Track2Hard
            args:
                root: data/AIC20_ReID/image_train
                csv_path: data/list/reid_query_hard.csv
                json_path: data/list/train_image_metadata.json
                train: True
        gallery:
            name: AIC2020Track2Hard
            args:
                root: data/AIC20_ReID/image_train
                csv_path: data/list/reid_query_hard.csv
                json_path: data/list/train_image_metadata.json
                train: False
scheduler:
    name: StepLR
    args:
        step_size: 8
        gamma: 0.1
        last_epoch: -1
dataset:
    train:
        name: TripletDataset
        args:
            dataset:
                name: AIC2020Track2
                args:
                    root: data/AIC20_ReID/image_train
                    path: data/list/reid_train_easy.csv
                    train: True
        loader:
            name: DataLoader
            args:
                batch_size: 8
                pin_memory: True
                shuffle: True
    val:
        name: TripletDataset
        args:
            dataset:
                name: AIC2020Track2
                args:
                    root: data/AIC20_ReID/image_train
                    path: data/list/reid_gallery_easy.csv
                    train: False
        loader:
            name: DataLoader
            args:
                batch_size: 8
                pin_memory: True
trainer:
    nepochs: 10
    val_step: 1
    log_step: 100