settings:
  dataset:
    train:
      name: ImageClassificationDataset
      args:
        root: train
    val:
      name: ImageClassificationDataset
      args:
        root: testing
    # augmentations:
    #   image_size: [256,256]
    #   horizontal_flip: 0
    #   shear: 0
    #   rotation: 0
    #   colorjitter:
    #     brightness: 0
    #     constrast: 0
    #     saturation: 0
    #     hue: 0
    #   cutout: 0

  model:
    name: Classifier
    args:
      backbone:
        name: ResNetExtractor
        args:
          version: resnet152
      n_classes: 5

  optimizer:
    name: AdamW # Adam, AdaS
    args:

  scheduler:
    name: ReduceLROnPlateau
    args:
      mode: min
      factor: 0.5
      patience: 5
      verbose: True

  criterion:
    name: CrossEntropyLoss
    args:

  metrics:
    - name: ClassificationF1Score
      args:
        types:

    - name: ClassificationAccuracyMetric
      args:
        types:
